In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import json
import numpy as np
from sklearn.model_selection import train_test_split
import itertools

In [2]:
df = pd.read_csv('finalDF.csv',index_col=0)
df = df.drop(columns=['glucose','diagnosis_tokenized'])
display(df)

hadm_id  subject_id  expire_flag  \
0     101216        8231            0   
1     123860         188            0   
2     194053        9965            0   
3     106909         286            0   
4     173194       18902            0   
5     126769         671            0   
6     117876         357            0   
7     171423        4392            0   
8     169538         402            0   
9     120845         263            0   
10    132401         188            1   
11    102959        9311            0   
12    143045          13            0   
13    188386        8698            1   
14    130275        4313            0   
15    111143       23780            1   
16    143334         323            0   
17    192031        8109            0   
18    109091       27150            0   
19    106862       16053            0   
20    148765       25009            0   
21    127976         239            0   
22    178509       10257            0   
23    100068        9889            0   
24    170681        2298            0   
25    190642         415            0   
26    186162       21786            0   
27    152578         294            0   
28    166852       13599            1   
29    184142       13806            1   
..       ...         ...          ...   
607   107085        9356            0   
608   171119        8799            0   
609   168571       21990            0   
610   170188        3543            0   
611   197882        3952            0   
612   185291        5771            0   
613   153621       17539            0   
614   161635         518            0   
615   144794        6063            0   
616   172079        6958            0   
617   140666        8698            0   
618   144187        2208            0   
619   135807         209            0   
620   110408       27083            0   
621   106374        6024            0   
622   138805        4113            0   
623   173420       23568            0   
624   189546        6917            0   
625   168672       11702            1   
626   164405         186            0   
627   134410        6448            0   
628   127958       22941            0   
629   199366       11421            0   
630   194340         305            1   
631   145084       21630            0   
632   185708       21955            0   
633   160948       21580            1   
634   106510        6917            0   
635   104739        1197            0   
636   159206        9622            0   

                                             diagnosis admission_type  age  \
0                          PERIPJERAL VASCULAR DISEASE      EMERGENCY   78   
1                               HEPATIC ENCEPHALOPATHY      EMERGENCY   55   
2                                       ABDOMINAL PAIN      EMERGENCY  307   
3                            ASTHMA, COPD EXACERBATION      EMERGENCY   85   
4                                   CAD, RENAL FAILURE      EMERGENCY   78   
5                              SUBARACHNOID HEMORRHAGE      EMERGENCY   47   
6                                ALTERED MENTAL STATUS      EMERGENCY   64   
7                                           BACTEREMIA      EMERGENCY   48   
8                       PULMONARY HYPERTENSION;SYNCOPE      EMERGENCY   49   
9                  PERIPHERAL INSUFFICIENCY;RIGHT FOOT      EMERGENCY   56   
10                                           BACK PAIN      EMERGENCY   56   
11   CARDIOMYOPATHY\IMPLANTABLE CARDIOVERTER DEFIBR...       ELECTIVE   78   
12                             CORONARY ARTERY DISEASE      EMERGENCY   40   
13                                               FEVER      EMERGENCY   85   
14                                         HYPOTHERMIA      EMERGENCY   31   
15   CORONARY ARTERY DISEASE; CONGESTIVE HEART FAIL...      EMERGENCY   86   
16                                    SEPSIS;TELEMETRY      EMERGENCY   58   
17                                  MYOCARDIAL INFARCT    

In [3]:
overfitting = df.loc[df['expire_flag'] == 1]

df = df.append(overfitting,ignore_index=True)
df = df.append(overfitting,ignore_index=True)
df = df.append(overfitting,ignore_index=True)
df = df.append(overfitting,ignore_index=True)
df = df.append(overfitting,ignore_index=True)

In [4]:
features = df.drop(columns=['hadm_id','subject_id','expire_flag',
                            'diagnosis','admission_type'])
pydf = df.values
print(pydf.shape)
X = pydf[:,5:470]
y = pydf[:,2]

(1042, 469)
[[78 1 71.0 ... 0.0 0.0 0.0]
 [55 1 160.0 ... 0.0 0.0 0.0]
 [307 1 224.0 ... 0.0 0.0 0.0]
 ...
 [76 1 272.0 ... 0.0 0.0 0.0]
 [77 1 224.0 ... 0.0 0.0 0.0]
 [79 1 343.0 ... 0.0 0.0 0.0]]
[0 0 0 ... 1 1 1]


In [ ]:
from sklearn.ensemble import ExtraTreesClassifier

XImp = pydf[:,5:470]
yImp = pydf[:,2]
xImp = np.asarray(XImp,dtype=np.float64)
yImp = np.asarray(yImp,dtype=np.float64)
forest = ExtraTreesClassifier()
forest.fit(XImp,yImp)
importances = forest.feature_importances_
std = np.std([tree.feature_importances_ for tree in forest.estimators_],
             axis=0)
indices = np.argsort(importances)[::-1]

# Print the feature ranking
print("Feature ranking:")

for f in range(20):
    print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))

# Plot the feature importances of the forest
plt.figure()
plt.title("Feature importances")
plt.bar(range(X.shape[1]), importances[indices],
       color="r", yerr=std[indices], align="center")
plt.xticks(range(X.shape[1]), indices)
plt.xlim([-1, 19])
plt.show()

In [ ]:
import seaborn as sns
d = df[['expire_flag','age','admission_type_encoded','0','1','2','3','4','5','a','b','c']].copy()
corr = d.corr()
mask = np.zeros_like(corr, dtype=np.bool)
mask[np.triu_indices_from(mask)] = True
f, ax = plt.subplots(figsize=(11, 9))
cmap = sns.diverging_palette(220, 10, as_cmap=True)
sns.heatmap(corr, mask=mask, cmap=cmap, vmax=.3, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5})